---
# APT Installed Packages
# List of packages to be installed via apt.
apt_installed_packages:
  - git
  - build-essential
  - cmake
  - gdb
  - lcov
  - pkg-config
  - libbz2-dev
  - libffi-dev
  - libgdbm-dev
  - libgdbm-compat-dev
  - liblzma-dev
  - libncurses5-dev
  - libreadline6-dev
  - libsqlite3-dev
  - libssl-dev
  - lzma
  - tk-dev
  - uuid-dev
  - zlib1g-dev
  - libmpdec-dev
  - libzstd-dev
  - inetutils-inetd
  - dkms
  - xz-utils
  - pipx
  - luarocks
  - neovim
  - tmux
  - htop
  - duf
  - bat
  - fish
  - btop

# Installed Applications from the App Center
# List of applications to install from the App Center.
snap_installed_apps:
  - firefox
  - name: alacritty
    classic: true
  - steam
