---
- name: Include distribution-specific vars.
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
      - macos.yml
  when: ansible_distribution == "MacOSX"

- name: Ensure Oh My Zsh required homebrew packages are installed.
  community.general.homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
  loop: "{{ __oh_my_zsh_homebrew_required_packages }}"
  when: ansible_distribution == "MacOSX"
